#!/bin/bash

COMMON_OPTS="
    --benchmark_color=true
    --benchmark_counters_tabular=true
    --benchmark_display_aggregates_only=true
    --benchmark_report_aggregates_only=true
"

BIN_PATH="bin/benchmarks"

run_test() {
    test_exe="$1"
    shift
    opts="$@"
    test_path="$BIN_PATH/$test_exe"

    make -j2 "$test_path" && \
        "$test_path" $COMMON_OPTS $opts \
            --benchmark_out="./logs/$test_exe.log" \
            --benchmark_out_format="console"
}

run_bench() {
    test_exe="$1"
    shift
    opts="$@"
    test_path="$BIN_PATH/$test_exe"

    make -j2 "$test_path" && \
    perf record -g -- "$test_path" $COMMON_OPTS $opts \
        --benchmark_out="./logs/$test_exe.log" \
        --benchmark_out_format="console" && \
    perf report -g "graph,0.5,caller"
}

if [ $# -gt 0 ]; then
    run_test "$@"
    # run_bench "$@"
else
    run_test \
        "vector_benchmark" \
        "--benchmark_filter=vector,.(std::array|std::string)" \
        "--push_cons_dest"
fi
