#!/bin/sh

./run-with-saving \
    vector_benchmark_push_only_1 \
    ./run-current vector_benchmark \
        --push_only \
        --num_env_vectors=1 \
        --int_arg=4500 \
        --string_arg=1700 \
        --array_arg=2000 \
        --test_type_arg=3500 \
        --T_test_type_arg=3500 \
        $@