#!/bin/sh

./run-with-saving \
    vector_benchmark_push_only_50 \
    ./run-current vector_benchmark \
        --push_only \
        --num_env_vectors=50 \
        --int_arg=1800 \
        --string_arg=700 \
        --array_arg=700 \
        --test_type_arg=1300 \
        --T_test_type_arg=1000 \
        $@