#!/bin/sh

./run-current vector_benchmark \
    --push_only \
    --common_iters=1 \
    --int_arg=4000 \
    --string_arg=1700 \
    --array_arg=1500 \
    --test_type_arg=2000 \
    --T_test_type_arg=3000
