#!/bin/sh

if [ "$1" = "static" ]; then
    arg="static"
    shift
fi

if [ "$arg" = "static" ]; then
    ./run-current static_vector_benchmark \
        --all \
        --int_arg=2000 \
        --string_arg=1000 \
        --test_type_arg=1500 \
        --array_arg=1000 \
        $@
else
    ./run-current vector_benchmark \
        --all \
        --int_arg=2000 \
        --string_arg=1000 \
        --array_arg=1100 \
        --test_type_arg=1300 \
        --T_test_type_arg=1300 \
        $@
fi
