#!/bin/sh

./run-with-saving \
    vector_benchmark_push_only_100 \
    ./run-current vector_benchmark \
        --push_only \
        --num_env_vectors=100 \
        --int_arg=1200 \
        --string_arg=400 \
        --array_arg=500 \
        --test_type_arg=500 \
        --T_test_type_arg=500 \
        $@